OO syntax and more-minimal examples
learn-co-curriculum/dsc-data-viz pull request #2
Opened 2021-01-06 00:12 UTC by hoffm386

## Object-Oriented Syntax

According to [this tutorial on the Matplotlib website](https://matplotlib.org/tutorials/introductory/lifecycle.html):

> In general, try to use the object-oriented interface over the pyplot interface.

So, **instead of introducing the PyPlot interface, this rewrite introduces the object-oriented interface first**. At some point we will still want to introduce the PyPlot interface, but that seems like it can wait until later.

In order to help students navigate the documentation + Googling (where the PyPlot interface inevitably appears), this version adds links to the `Axes` documentation for each type of plot.

## More-Minimal Examples

The plots in the current version start out by showing 3 lines of NumPy code, then 4 lines of Matplotlib code. I think that's a lot to digest for someone who is new to the material. This version **starts with just 1 line of Matplotlib code** showing an empty plot.

After that, I **start each plot by showing just the 2 lines of code needed to create the figure and axes then make the plot, then secondarily add the labels**, instead of having 4-7 lines as the first time they see a plot.

This version also **removes any customization other than adding labels** (title, X and Y axis, legend), since I think that distracts from the main point. The exception is the `bins` argument on the histograms, where this version sets both `bins` and `edgecolor` because I think that makes a material difference in what is being plotted.

## NumPy

Instead of saying that we will cover NumPy more formally later, this version **emphasizes that NumPy is only being used as a teaching tool and that they are supposed to be focused on the Matplotlib content**. This allows this lesson to be used more flexibly within the curriculum, and hopefully avoids distraction from the main point.

## Lesson Organization/Motivation

The current version dives in, assuming that you don't know anything about plots but also that you know why it's useful to make plots with Python. This version adds:

- a heading and some images at the top introducing what Matplotlib can do
- language of "reviewing some of the most essential types of plots" instead of assuming they have never heard of these plots before
- subheadings within each type of plot separating the "what" (general concepts of these plots) from the "how" (with Matplotlib)

2021-01-21 19:34 UTC, Ben-Oren requested changes

2021-01-21 19:34 UTC, Ben-Oren commented on README.md
> +Recall, the y-axis tells you how often a certain range of numbers appears in the data set. From the histogram (interpreting these dummy numbers as though they were real), you can see that there are a
Rewrote the last sentence to remove "significantly" so there's not an implication of a statistical test being done:

There are a quarter as many people who retire at 75 as 65 (40 people vs 10 people), and even fewer who retire at 50 (2 people).

2021-01-22 17:06 UTC, hoffm386 commented on README.md
> +Recall, the y-axis tells you how often a certain range of numbers appears in the data set. From the histogram (interpreting these dummy numbers as though they were real), you can see that there are a
Added, although I reversed 40 and 10 so they are in the same order as 75 and 65

2021-01-22 17:50 UTC, Ben-Oren commented on README.md
> +Recall, the y-axis tells you how often a certain range of numbers appears in the data set. From the histogram (interpreting these dummy numbers as though they were real), you can see that there are a
Whoops, good catch

2021-01-22 17:51 UTC, Ben-Oren approved these changes

2021-01-22 20:28 UTC, merged